//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garipov_PM01
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEPARTAMENT()
        {
            this.DOCTORS = new HashSet<DOCTORS>();
        }
    
        public int DEPARTAMENT_ID { get; set; }
        public string DEPARTAMENT_NAME { get; set; }
        public string DEPARTAMENT_FLOOR { get; set; }
        public string DEPARTAMENT_MANAGER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCTORS> DOCTORS { get; set; }
    }
}
