//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garipov_PM01
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIAGNOSIS()
        {
            this.MEDICAL_HISTORY = new HashSet<MEDICAL_HISTORY>();
        }
    
        public int DIAGNOSIS_ID { get; set; }
        public string DIAGNOSIS_NAME { get; set; }
        public string DIAGNOSIS_SIGNS { get; set; }
        public string DIAGNOSIS_PERIOD { get; set; }
        public string DIAGNOSIS_PURPOSE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_HISTORY> MEDICAL_HISTORY { get; set; }
    }
}
