//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garipov_PM01
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCTORS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOCTORS()
        {
            this.MEDICAL_HISTORY = new HashSet<MEDICAL_HISTORY>();
        }
    
        public int DOCTOR_ID { get; set; }
        public string DOCTOR_NAME { get; set; }
        public string DOCTOR_SURNAME { get; set; }
        public string DOCTOR_PATRONYMIC { get; set; }
        public string DOCTOR_POST { get; set; }
        public string DOCTOR_SCIENTIFIC { get; set; }
        public System.DateTime DOCTOR_EXPERIENCE { get; set; }
        public string DOCTOR_ADRESS { get; set; }
        public int DOCTOR_DEPARTAMENT_ID { get; set; }
        public Nullable<int> DOCTOR_WORK { get; set; }
        public string DOCTOR_PHOTO { get; set; }
        public string DEPART_NAME
        {
            get
            {
                return this.DEPARTAMENT?.DEPARTAMENT_NAME ?? "Отделение не найдено";
            }
        }




        public virtual DEPARTAMENT DEPARTAMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_HISTORY> MEDICAL_HISTORY { get; set; }
    }
}
