//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garipov_PM01
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PATIENTS()
        {
            this.MEDICAL_HISTORY = new HashSet<MEDICAL_HISTORY>();
        }
    
        public int PATIENT_ID { get; set; }
        public string PATIENT_NAME { get; set; }
        public string PATIENT_SURNAME { get; set; }
        public string PATIENT_PATRONYMIC { get; set; }
        public string PATIENT_ADRESS { get; set; }
        public string PATIENT_CITY { get; set; }
        public System.DateTime PATIENT_BIRTHDATE { get; set; }
        public string PATIENT_GENDER { get; set; }
        public Nullable<int> PATIENT_AGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_HISTORY> MEDICAL_HISTORY { get; set; }
    }
}
